### ISSUE TITLE
Aigis 路线图 / Aigis Roadmap

### ISSUE THREAD

**Issue by iamhyc** [iamhyc/Aigis#28]
**Release v2.0.0**
- [ ] Group Management
  - CRUD via `Chip`, or on Edit Page
- [ ] Master Key Upgrade: PBKDF2 (v2) --> Scrypt (v3)
- [ ] Dynamic Card Add Action (on Item Swipe Action) (#29)
  - Hindered by ***Defect*** of `AddFormMenuItem` Component
- [ ] Edit & Update Dynamic Card
  - Reference: https://developer.huawei.com/consumer/cn/forum/topic/0204156424510289030?fid=0109140870620153026
- [ ] Audit Log
  -  Rollout with 30 days or 10 MB limit
- [ ] ATL3 Authentication Support

**Comment by iamhyc** [comment]
Release v1.0.0 (2024/11/29)

**Release v1.1.0** (2024/12/06)

- [ ] When Master Key Not Available
  - Display Share QR Code & Link on Edit Page
- [ ] Correct Usage Statistics
  - Usage Count / Last Used Time / First Added Time
- [ ] Support Import SVG Icon on Edit Page (#27)

**Comment by iamhyc** [comment]
**Release v0.8.0** (2024/12/14)
- [ ] Change KDF Algorithm to Native PBKDF2 (#34)
- [ ] Dynamic Card Support
  - on Item Swipe Action, on Title Bar
  - Need Auth to Access on Desktop (?)
  - Tap to Refresh

Release v1.0.0 (????/??/??)
- [x] Correctness of Scrypt (in TypeScript)
- [ ] Enable AOT for High Performance (Hindered by ArkTS)
- [ ] Aegis-compatible Import & Export

**Comment by iamhyc** [comment]
Release v1.0.0 (2024/12/31)
- [ ] Adaptive Columns to Wide Screen
- [ ] View Mode (#25)
  - Dynamic / Compact / Normal / Wide
- [ ] Scrypt Support for Aegis Compatibility
  - ~~Correctness of Scrypt in TypeScript~~
  - Scrypt Implementation in Native C
  - Aegis-compatible Import & Export

**Comment by iamhyc** [comment]
v1.0.0已于12月26日发布，但是被审核拖延至2025年 😅 祝大家新年快乐！2025年再见！/ v1.0.0 was released on December 26, but was delayed by the auditors until 2025 😅 so happy new year to all! See you in 2025！

P.S. [2024年开发日志](https://sudofree.xyz/p/developer-log-aigis-authenticator-for-harmonyos-next/) (in Chinese only)
